<?php //include("_inc/header.php"); ?>
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Research America Inc. Named Top Market Research Company By GreenBook</title>
      <meta name="description" content="Research America Inc was named to the 2019 Greenbook Market Leaders Report, coming in as the 50th largest firm in the industry">
      
      <link rel="canonical" href="https://researchamericainc.com/RAI-named-top-company-by-greenbook.php">

  <link rel="stylesheet" href="./_js/owl-carousel/owl.carousel.css">
  <link rel="stylesheet" href="./_js/owl-carousel/owl.theme.css">
  <link href="https://fonts.googleapis.com/css?family=Open+Sans:400,700|Roboto" rel="stylesheet">
  <link rel="stylesheet" href="//cdn.jsdelivr.net/jquery.sidr/2.2.1/stylesheets/jquery.sidr.light.min.css">
  <link href="http://vjs.zencdn.net/5.19.2/video-js.css" rel="stylesheet">
  <script src="http://vjs.zencdn.net/ie8/1.1.2/videojs-ie8.min.js"></script>

  <link href="./_css/style.css" rel="stylesheet">
  <link rel="shortcut icon" href="favicon.ico" type="image/x-icon">
     
  <!-- Google Tag Manager -->
<script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
})(window,document,'script','dataLayer','GTM-T28PP6C');</script>
<!-- End Google Tag Manager -->
      
      <!-- JSON-LD markup generated by Google Structured Data Markup Helper. -->
<script type="application/ld+json">
{
  "@context" : "http://schema.org",
  "@type" : "Article",
  "name" : "Research America Inc. Named Top Market Research Company By GreenBook",
  "author" : {
    "@type" : "Person",
    "name" : "Research America Inc"
  },
  "datePublished" : "2019-12-13",
  "image" : "https://researchamericainc.com/_img/new_page.png",
  "articleBody" : "According to Robert Porter, CEO, “Research America has enjoyed explosive growth across our business segments. the moments that capture us at our best—are moments of courage and change against the status quo. Milestone moments that build on each employee’s specific behaviors. Effective recognition makes employees feel noticed for what they have done. Introducing a challenge in business and analysis creating a defining moment to solve this problem. greater customer satisfaction and loyalty year after year.”",
  "publisher" : {
    "@type" : "Organization",
    "name" : "Research America Inc"
  }
}
</script>
      
</head>
    
    
<body>
<!-- Google Tag Manager (noscript) -->
<noscript><iframe src="https://www.googletagmanager.com/ns.html?id=GTM-T28PP6C"
height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>
<!-- End Google Tag Manager (noscript) -->

<div class="container">
<div class="row" id="main-header">
  <div class="header-logo">
    <a href="/">
      <img src="_img/research-america-logo-new2.png" class="main-header-logo" alt="Research America INC">
    </a>
    <a href="/" class="home_top">HOME</a>
    <a id="open-mobile-menu" href="#sidr">
      <img src="_img/open-mobile-menu.png">
    </a>
  </div>
  <div class="header-number">
    <p>
      <a href="tel:1-610-356-1800">Call an Expert!  (610) 356-1800</a>
    </p>
  </div>
</div>
<!--ooo000ooo -->
<?php include("_inc/citiesbar_inc.php"); ?>
<!-- above div with id page-header -->
<!--ooo000ooo -->
<div class="row" id="page-header">

	<img src="_img/new_page.png">

	

	<?php include("_inc/menu-bar.php"); ?>

</div>



<div class="row" id="main-page-content">

<div class="inside">
	
	
	<h1>Research America Inc. Named Top Market Research Company By GreenBook</h1>

		

	
<p>December 13, 2019 - Newtown Square, PA: After being named to the INC 5000 earlier this year, Research America Inc was named to the 2019 Greenbook Market Leaders Report, coming in as the 50th largest firm in the industry (showing a 34.9% increase in U.S. revenue).
 </p>
	
	<p>According to Robert Porter, CEO, “Research America has enjoyed explosive growth across our business segments. the moments that capture us at our best—are moments of courage and change against the status quo. Milestone moments that build on each employee’s specific behaviors. Effective recognition makes employees feel noticed for what they have done. Introducing a challenge in business and analysis creating a defining moment to solve this problem. greater customer satisfaction and loyalty year after year.”</p>

		
		
		
	<p><b>ABOUT RESEARCH AMERICA…</b> RAI is an award-winning, family-owned and operated company providing <a href="./marketing-research.php">market research services</a> for over 30 years. They employ 300 researchers in 15 cities providing the qualitative and quantitative research necessary for their clients to make the right business decisions with confidence. They have deep expertise in Energy, Healthcare, Government, Professional Services and all manner of B2B and B2C research.  To learn more, go to: <a href="./">www.researchamericainc.com</a> or call (610) 356-1800.</p>

	
	
</div>

</div>


<?php include("_inc/insight-ux.php"); ?>

<?php include("_inc/footer.php"); ?>